name: rhvix
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  file_picker: ^6.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/logo.svg
    - images/notify.svg
    - images/point.svg
    - images/calendar.svg
    - images/man.svg
    - images/work.svg
    - images/woman.svg
    - images/notify_present.svg


  uses-material-design: true

